version: '3'

services:
  activemq:
    image: codingpuss/activemq:5.17.2-jre-19-alpine
    environment:
      ACTIVEMQ_OPTS: "-Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"
    ports:
      - "61616:61616"
      - "8161:8161"
